#!/usr/bin/env python
"""MiniHack path (1): run a MiniHack .des level on the NetHack-engine fork
(/root/NetHack-engine, package nethack_core, ctypes -> libnethack.so) and use
its native EngineEnv.snapshot()/restore() for branching.

How the level gets in: MiniHack itself works by compiling the task's .des with
NetHack's `lev_comp` into `mylevel.lev`, packing it with MiniHack's own compiled
`dungeon` (whose first level is "mylevel") into a DLB archive `nhdat`, and
pointing NetHack at that archive. The fork ships the same `lev_comp`/`dlb`
utilities (third_party/NetHack/src/build/util) and RawEngine takes a `datadir`
override for the read-only data tree, so we do the same thing here:

  1. obtain the task's .des (file from minihack/dat, or the generated
     `mylevel.des` MiniHack writes for procedurally built tasks like Boxoban)
  2. fork lev_comp: mylevel.des -> mylevel.lev
  3. fork dlb: extract the fork's nhdat, drop in MiniHack's `dungeon` +
     mylevel.lev, re-pack -> patched nhdat inside a fresh datadir
  4. monkeypatch RawEngine._build_dat_path -> patched datadir; EngineEnv()

Then: K prefix keystrokes, snapshot(), 3x [restore(), ^R, 50 fixed keystrokes],
assert identical observation traces (the live env is mutated between restores),
timings.

Two engine-specific details a Go-Explore layer must replicate:
  * `--More--` prompts swallow ordinary keystrokes; like BALROG's AutoMore
    wrapper we send MORE (13) until the prompt is gone.
  * restore() rewinds the game state but the tty mirror can keep stale rows
    from the branch played before the restore; a ^R (18, redraw, takes no game
    time) right after restore() makes tty_chars/tty_colors identical too.
    `--no-redraw` shows the failure mode.

Needs: PYTHONPATH=/root/NetHack-engine and the BALROG venv (for `minihack`'s
.des files / generated levels). No LLM calls.
"""
from __future__ import annotations

import argparse
import inspect
import os
import re
import shutil
import subprocess
import sys
import tempfile
import traceback
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import Timer, banner, compare_traces, fingerprint, fixed_actions, write_result  # noqa: E402

ENGINE_ROOT = Path(os.environ.get("NETHACK_ENGINE_ROOT", "/root/NetHack-engine"))
BUILD = ENGINE_ROOT / "third_party" / "NetHack" / "src" / "build"
UTIL = BUILD / "util"
FORK_DAT = BUILD / "dat"
MORE, REDRAW = 13, 18
BL_TIME = 20  # blstats index of the game turn counter


def task_des_text(task: str) -> tuple[str, str]:
    """Return (des_text, source) for a MiniHack gym task id."""
    import gym
    import minihack  # noqa: F401
    from minihack.base import PATH_DAT_DIR

    env = gym.make(task)
    inner = env.unwrapped
    gen = os.path.join(inner.nethack._vardir, "mylevel.des")
    if os.path.exists(gen):  # procedurally generated (Boxoban, ...)
        text, src = open(gen).read(), f"generated by minihack ({task}) -> {gen}"
    else:  # file-based task: des_file="..." in the class __init__
        m = re.search(r'des_file="([^"]+\.des)"', inspect.getsource(type(inner).__init__))
        if not m:
            raise RuntimeError(f"cannot determine des file for {task}")
        src = os.path.join(PATH_DAT_DIR, m.group(1))
        text = open(src).read()
    env.close()
    return text, src


def build_patched_datadir(des_text: str, workdir: Path) -> Path:
    from minihack.base import LIB_DIR  # minihack/lib: compiled `dungeon` whose first level is "mylevel"

    workdir = Path(workdir).resolve()  # dlb/lev_comp run with cwd inside workdir
    workdir.mkdir(parents=True, exist_ok=True)
    comp = workdir / "comp"
    shutil.rmtree(comp, ignore_errors=True)
    comp.mkdir()
    (comp / "mylevel.des").write_text(des_text)
    r = subprocess.run([str(UTIL / "lev_comp"), "mylevel.des"], cwd=comp, capture_output=True, text=True)
    if r.returncode != 0 or not (comp / "mylevel.lev").exists():
        raise RuntimeError(f"fork lev_comp failed rc={r.returncode}: {r.stdout} {r.stderr}")
    ext = workdir / "extract"
    shutil.rmtree(ext, ignore_errors=True)
    ext.mkdir()
    subprocess.run([str(UTIL / "dlb"), "xf", str(FORK_DAT / "nhdat")], cwd=ext, check=True, capture_output=True)
    shutil.copy(os.path.join(LIB_DIR, "dungeon"), ext / "dungeon")
    shutil.copy(comp / "mylevel.lev", ext / "mylevel.lev")
    datadir = workdir / "datadir"
    shutil.rmtree(datadir, ignore_errors=True)
    datadir.mkdir()
    members = sorted(p.name for p in ext.iterdir())
    subprocess.run([str(UTIL / "dlb"), "cf", str(datadir / "nhdat")] + members, cwd=ext, check=True, capture_output=True)
    for p in FORK_DAT.iterdir():  # plain-file fallbacks (dlb falls back to fopen)
        if p.name not in ("nhdat", "dungeon", "CMakeFiles"):
            os.symlink(p, datadir / p.name)
    shutil.copy(os.path.join(LIB_DIR, "dungeon"), datadir / "dungeon")
    shutil.copy(comp / "mylevel.lev", datadir / "mylevel.lev")
    return datadir


def tty_to_text(tty) -> str:
    return "\n".join(bytes(r).decode("latin-1").rstrip() for r in tty)


def obs_record(obs, done, info) -> dict:
    return {
        "tty_chars": fingerprint(obs.tty_chars),
        "tty_colors": fingerprint(obs.tty_colors),
        "tty_cursor": fingerprint(obs.tty_cursor),
        "glyphs": fingerprint(obs.glyphs),
        "chars": fingerprint(obs.chars),
        "colors": fingerprint(obs.colors),
        "blstats": fingerprint(obs.blstats),
        "message": bytes(obs.message).split(b"\0")[0].decode("latin-1"),
        "inv_strs": fingerprint(obs.inv_strs),
        "inv_letters": fingerprint(obs.inv_letters),
        "done": bool(done),
        "info": str(info),
    }


class Driver:
    """EngineEnv + AutoMore-style prompt handling (mirrors BALROG's AutoMore)."""

    def __init__(self, env):
        self.env = env
        self.more_dismissed = 0

    def _has_more(self) -> bool:
        return b"--More--" in bytes(self.env._engine.tty_chars[0]) or "--More--" in tty_to_text(self.env._engine.tty_chars)

    def dismiss_more(self):
        n = 0
        while self._has_more() and n < 20:
            self.env.step(MORE)
            self.more_dismissed += 1
            n += 1

    def step(self, a):
        obs, done, info = self.env.step(a)
        if not done:
            self.dismiss_more()
            obs = self.env._engine.to_core_observation()
        return obs, done, info

    def play(self, actions, timer=None):
        trace = []
        for a in actions:
            if timer is not None:
                with timer:
                    o, d, i = self.step(a)
            else:
                o, d, i = self.step(a)
            trace.append(obs_record(o, d, i))
            if d:
                break
        return trace


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", default="MiniHack-Quest-Easy-v0")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--prefix", type=int, default=30)
    ap.add_argument("--branch", type=int, default=50)
    ap.add_argument("--no-redraw", action="store_true", help="do NOT send ^R after restore (shows stale-tty failure)")
    ap.add_argument("--workdir", default=None)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    tag = f"{args.task}{'_noredraw' if args.no_redraw else ''}"
    out = args.out or os.path.join(os.path.dirname(os.path.abspath(__file__)), "results", f"minihack_engine_{tag}.json")
    workdir = Path(args.workdir or tempfile.mkdtemp(prefix="mh_engine_"))
    result = {"env": "minihack-engine", "task": args.task, "seed": args.seed, "engine_root": str(ENGINE_ROOT),
              "redraw_after_restore": not args.no_redraw}
    banner(f"MiniHack on NetHack-engine fork: task={args.task} seed={args.seed} redraw={not args.no_redraw} workdir={workdir}")

    try:
        des_text, src = task_des_text(args.task)
        result["des_source"] = src
        datadir = build_patched_datadir(des_text, workdir)
        result["datadir"] = str(datadir)
        print("des source:", src, "\npatched datadir:", datadir)
    except Exception as e:  # noqa: BLE001
        result.update(ok=False, error=f"level build failed: {type(e).__name__}: {e}")
        traceback.print_exc()
        write_result(out, result)
        return 1

    sys.path.insert(0, str(ENGINE_ROOT))
    import nethack_core._engine as E
    from nethack_core.actions import CompassDirection, Command
    from nethack_core.engine_env import EngineEnv

    E.RawEngine._build_dat_path = lambda self: datadir  # point the engine at the patched data tree

    env = EngineEnv()
    env.seed(args.seed)
    obs, meta = env.reset()
    drv = Driver(env)
    drv.dismiss_more()
    obs = env._engine.to_core_observation()
    first_frame = tty_to_text(obs.tty_chars)
    print(first_frame)
    result["first_frame"] = first_frame
    result["observation_fields"] = list(obs.__dataclass_fields__)
    t0 = int(obs.blstats[BL_TIME])

    keys = [int(k) for k in CompassDirection][:4] + [int(Command.SEARCH)]
    prefix = fixed_actions(keys, args.prefix, seed=args.seed * 7919)
    branch = fixed_actions(keys, args.branch, seed=args.seed * 104729)
    mutate = fixed_actions(keys, 20, seed=args.seed * 15485863)

    step_t, snap_t, rest_t = Timer(), Timer(), Timer()
    ptrace = drv.play(prefix, step_t)
    t1 = int(env._engine.blstats[BL_TIME])
    print(f"prefix: {len(ptrace)} steps, game turn {t0} -> {t1}, --More-- dismissed so far: {drv.more_dismissed}")
    print(tty_to_text(env._engine.tty_chars))
    result.update(prefix_len=len(ptrace), turn_after_prefix=t1, turn_at_reset=t0,
                  episode_ended_in_prefix=bool(ptrace and ptrace[-1]["done"]))
    if ptrace and ptrace[-1]["done"]:
        print("episode ended during prefix; nothing to branch from")
        result.update(ok=False, error="episode ended during prefix")
        write_result(out, result)
        return 1

    def restore(h):
        with rest_t:
            env.restore(h)
            if not args.no_redraw:
                env.step(REDRAW)
        drv.dismiss_more()

    with snap_t:
        h = env.snapshot()
    restore(h)
    b1 = drv.play(branch, step_t)
    drv.play(mutate)  # mutate the live env (aliasing probe)
    restore(h)
    b2 = drv.play(branch, step_t)
    h2 = env.snapshot()  # a second snapshot of a different state must not disturb h
    drv.play(mutate)
    env.restore(h2)
    drv.play(mutate)
    env.free_snapshot(h2)
    restore(h)
    b3 = drv.play(branch, step_t)

    ident = compare_traces(b1, b2, "engine b1-vs-b2") and compare_traces(b2, b3, "engine b2-vs-b3")
    state_keys = ("glyphs", "chars", "colors", "blstats", "message", "inv_strs", "inv_letters", "done")
    strip = lambda tr: [{k: r[k] for k in state_keys} for r in tr]  # noqa: E731
    ident_state = compare_traces(strip(b1), strip(b2), "engine game-state only b1-vs-b2") and \
        compare_traces(strip(b2), strip(b3), "engine game-state only b2-vs-b3")
    result.update(
        ok=bool(ident),
        identical_branches=ident,
        identical_branches_game_state_only=ident_state,
        no_alias=ident,  # b2/b3 were taken after the live env was mutated post-restore and after another snapshot/restore
        snapshot_ms=snap_t.mean_ms,
        restore_ms=rest_t.mean_ms,
        step_ms=step_t.mean_ms,
        branch_len=len(b1),
        more_dismissed_total=drv.more_dismissed,
        final_frame_branch=tty_to_text(env._engine.tty_chars),
    )
    print(f"snapshot={snap_t.mean_ms:.3f}ms restore(+redraw)={rest_t.mean_ms:.3f}ms step={step_t.mean_ms:.3f}ms "
          f"identical(all obs)={ident} identical(game state)={ident_state} branch_len={len(b1)}")
    env.free_snapshot(h)
    env.close()
    write_result(out, result)
    return 0 if ident else 1


if __name__ == "__main__":
    sys.exit(main())
